# Generated by Django 3.0.4 on 2020-04-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('indicaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('precioTotal', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
