# Generated by Django 3.0.4 on 2020-04-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentopedido',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamentopedido',
            name='medicamento',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicamentos.Medicamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentopedido',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente'),
        ),
    ]
