# Generated by Django 3.0.4 on 2020-04-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente'),
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='cita',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eps.Cita'),
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='medicamentos',
            field=models.ManyToManyField(to='medicamentos.Medicamento'),
        ),
    ]
