# Generated by Django 2.2 on 2020-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
